# Generated by Django 5.2.11 on 2026-02-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(blank=True, max_length=20)),
                ('vehicle', models.CharField(max_length=100)),
                ('customer', models.CharField(blank=True, max_length=100)),
                ('complaint', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CHECKED_IN', 'Checked In'), ('DIAG', 'Diagnosing'), ('WAIT_CUST', 'Waiting on Customer'), ('WAIT_PARTS', 'Waiting on Parts'), ('IN_PROGRESS', 'In Progress'), ('READY', 'Ready for Pickup'), ('DONE', 'Completed'), ('CANCELLED', 'Cancelled')], default='CHECKED_IN', max_length=20)),
                ('promised_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
