# Generated by Django 5.2.11 on 2026-02-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='promised_at',
        ),
        migrations.AddField(
            model_name='workorder',
            name='promised_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
