# Generated by Django 5.2.11 on 2026-07-11 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_carforsale_carforsaleissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='workorder',
            name='intervention_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='workorder',
            name='intervention_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='workorder',
            name='intervention_3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='workorder',
            name='intervention_4',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='workorder',
            name='intervention_5',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='workorder',
            name='intervention_6',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='workorder',
            name='intervention_7',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='workorder',
            name='intervention_8',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='workorder',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='vin',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.CreateModel(
            name='WorkOrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('description', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('position', models.PositiveIntegerField(default=0)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='board.workorder')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
