# Generated by Django 5.2.11 on 2026-07-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_workorder_check_in_workorder_check_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalagreement',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('IT', 'Italian')], default='IT', max_length=2),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='return_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
